### ISSUE TITLE
Configure fails with Intel 19.x

### ISSUE THREAD

**Issue by naromero77** [FFTW/fftw3#184]
This bug appears when compiling FFTW 3.3.8 with the Intel 19.x compiler. It happens when configure is run, but it is quite easy to fix:

```
   '../configure' '--prefix=/scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/intel-19.0.3.199/fftw-3.3.8-mu4zpumx74wg62ckwkfu4ga7bpsus35w' '--enable-shared' '--enable-threads' '--enable-sse2' '--disable-avx' '--disable-avx2' '--disable-avx512' '--disable-avx-128-fma' '--disable-kcvi' '--disable-vsx' '--disable-neon' '--disable-fma'

1 error found in build log:
     177    checking for ptrdiff_t... no
     178    checking for uintptr_t... no
     179    checking size of void *... 0
     180    checking size of float... 0
     181    checking size of double... 0
     182    checking size of fftw_r2r_kind... 0
  >> 183    configure: error: sizeof(fftw_r2r_kind) test failed
```

The fix is to add `CFLAGS=-gcc-sys` flag.

More details here:
https://software.intel.com/en-us/forums/intel-c-compiler/topic/804830

And page 5 of this PDF:
https://software.intel.com/sites/products/collateral/hpc/compilers/intel_linux_compiler_compatibility_with_gnu_compilers.pdf

**Comment by RemiLacroix-IDRIS** [comment]
I am also running into this issue. It doesn't seem specific to the 19.x Intel compilers, I am able to reproduce with older versions too. I am sure those worked before so it must be somehow related to the operating system as we recently upgraded from Red Hat 7.6 to Red Hat 8.1.

The issue seems to be caused by the `-no-gcc` option which is automatically added when detecting the Intel compilers:
https://github.com/FFTW/fftw3/blob/78e01190450398d44c7ba7ac69d3e720b6af1f16/configure.ac#L333-L341

If I comment this snippet from the `configure`, FFTW builds just fine.

Maybe @stevengj can shed some light on why this was added in the first place?

**Comment by RemiLacroix-IDRIS** [comment]
> it must be somehow related to the operating system as we recently upgraded from Red Hat 7.6 to Red Hat 8.1.

In fact it has to do with the version of the GCC compiler available in the PATH.

On our machine, the system compiler is GCC 8.3.1 but we have older and newer versions available using the `module` command. The `configure` works with Intel compilers as long as the version of GCC available in the PATH is lower or equal to 6.5.0, it starts failing with GCC 7.3.0.

It feels like using `-gcc-sys` instead of `-no-gcc` could be a good idea:
> Defines GNU macros only during compilation of system headers.

I cannot be sure though.

**Comment by stevengj** [comment]
The `config.log` file should have the exact compiler error message that caused this test to fail.  (It's really long, but search through it for `fftw_r2r_kind` to find this specific test's output.)

**Comment by RemiLacroix-IDRIS** [comment]
I am attaching the full [config.log](https://github.com/FFTW/fftw3/files/4993055/config.log).

The first issue visible in the `configure` output is:
```
configure: WARNING: fcntl.h: present but cannot be compiled
configure: WARNING: fcntl.h:     check for missing prerequisite headers?
configure: WARNING: fcntl.h: see the Autoconf documentation
configure: WARNING: fcntl.h:     section "Present But Cannot Be Compiled"
configure: WARNING: fcntl.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------- ##
configure: WARNING:     ## Report this to fftw@fftw.org ##
configure: WARNING:     ## ---------------------------- ##
```
caused by:
```
In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(40):
/usr/include/bits/floatn-common.h(214): error: invalid combination of type specifiers
  typedef float _Float32;
                ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(40):
/usr/include/bits/floatn-common.h(251): error: invalid combination of type specifiers
  typedef double _Float64;
                 ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(40):
/usr/include/bits/floatn-common.h(268): error: invalid combination of type specifiers
  typedef double _Float32x;
                 ^

In file included from /usr/include/bits/floatn.h(119),
                 from /usr/include/stdlib.h(55),
                 from conftest.c(40):
/usr/include/bits/floatn-common.h(285): error: invalid combination of type specifiers
  typedef long double _Float64x;
                      ^
```

The same happens while checking other system headers and finally when checking the size of some types:
```
checking size of int... 0
checking size of unsigned int... 0
checking size of long... 0
checking size of unsigned long... 0
checking size of long long... 0
checking size of unsigned long long... 0
checking size of size_t... 0
checking size of ptrdiff_t... 0
checking for ptrdiff_t... no
checking for uintptr_t... no
checking size of void *... 0
checking size of float... 0
checking size of double... 0
checking size of fftw_r2r_kind... 0
configure: error: sizeof(fftw_r2r_kind) test failed
```

**Comment by boegel** [comment]
Using `-no-gcc` when building with Intel compilers was added a long time ago, see https://github.com/FFTW/fftw3/commit/7b90a23bc9ceeeb03131b4774aa0ff5d04e91c63. As far as I can tell the motivation was that old versions of the Intel compilers claimed they were GCC compatible while they were not, which is supported by this snippet of text from http://www.fftw.org/faq/section2.html#compilerCrashes:

```
Versions 8.0 and 8.1 of Intel's icc falsely claim to be gcc, so you should specify CC="icc -no-gcc";
this is automatic in FFTW 3.1. icc-8.0.066 reportely produces incorrect code for FFTW 2.1.5, but is fixed
in version 8.1. icc-7.1 compiler build 20030402Z appears to produce incorrect dependencies, causing
the compilation to fail. icc-7.1 build 20030307Z appears to work fine. (Use icc -V to check which build
you have.) As of 2003/04/18, build 20030402Z appears not to be available any longer on Intel's website,
whereas the older build 20030307Z is available. 
```

I think the right way forward here is to simply not use `-no-gcc` anymore when building with Intel compilers, it was a workaround for a problem that is no longer there in current Intel compilers.
I doubt anyone is still using Intel compiler versions from 2003 or older?

**Comment by RemiLacroix-IDRIS** [comment]
@boegel: I think you are right. I successfully compiled FFTW without `-no-gcc` nor `-sys-gcc` some times ago and we had no problem with the resulting build so far.

**Comment by stevengj** [comment]
Yes, we added `-no-gcc` 15 years ago when it was causing lots of bug reports (7b90a23bc9ceeeb03131b4774aa0ff5d04e91c63).   We stopped using it on MacOS 12 years ago (a5edcdb0c705b3b42f8aec48e41457fd3771bed7) because it was required by system headers there.   I think we can just get rid of this flag from the configure script now.
