### ISSUE TITLE
Deallocating string returned by fftw_sprint_plan

### ISSUE THREAD

**Issue by sbrisard** [FFTW/fftw3#238]
[Section 4.2 (Using Plans)](http://fftw.org/fftw3_doc/Using-Plans.html#Using-Plans) of the docs states that 

> This outputs a “nerd-readable” representation of the plan to the given file, to stdout, or two a newly allocated NUL-terminated string (which the caller is responsible for deallocating with free), respectively.

However, when trying to call `free` on the `char *` returned by `fftw_sprint_plan` leads to a crash on my computer.

Here is a minimal working example

```C
#include <stdlib.h>

#include <fftw/fftw3.h>

int main() {
  int n = 16;

  fftw_complex *in = (fftw_complex*) fftw_malloc(n * sizeof(fftw_complex));
  fftw_complex *out = (fftw_complex*) fftw_malloc(n* sizeof(fftw_complex));
  fftw_plan plan = fftw_plan_dft_1d(n, in, out, FFTW_FORWARD, FFTW_ESTIMATE);

  char* repr = fftw_sprint_plan(plan);
  printf(repr);

  free(repr);
  fftw_destroy_plan(plan);
  fftw_free(out);
  fftw_free(in);
}
```

The above code crashes. If I comment out ``free(repr)``, I get the following output

```
(dft-direct-16 "n1_16")
```

It seems to me that if I replace ``free(repr)`` with ``fftw_free(repr)``, then the crash does not occur (but I am not sure that the memory is indeed released).

Many thanks for a great library!

**Comment by stevengj** [comment]
`fftw_sprint_plan` [allocates its buffer with `malloc`](https://github.com/FFTW/fftw3/blob/e9c510bf92a4fa848982310d2ecc8c5701aa3f6a/api/print-plan.c#L33), so it should be deallocated with `free`.

It could be that FFTW was compiled to use a different `malloc` implementation than the one you are using for your code, maybe because you used different compilers?  What compiler are you using, vs. what compiler did you use to compile FFTW?

**Comment by sbrisard** [comment]
Thanks for the quick response.
Right, that might be the cause.
I used MSVC to compile the example, but use FFTW from `conda-forge`. Need to check how this was compiled. Still, it's surprising that `fftw_free` should work on this `char *`. Well, in fact I don't know that it works--only, it does not crash.
Will check

**Comment by stevengj** [comment]
With most compilers, `fftw_free` is [equivalent to `free`](https://github.com/FFTW/fftw3/blob/e9c510bf92a4fa848982310d2ecc8c5701aa3f6a/kernel/kalloc.c#L42), so it calls the correct `free` for FFTW's `malloc`.  The exception is if you compile FFTW with MSVC where we have to use [our own aligned `malloc`](https://github.com/FFTW/fftw3/blob/e9c510bf92a4fa848982310d2ecc8c5701aa3f6a/kernel/kalloc.c#L80), and ICC where [we use `_mm_free`](https://github.com/FFTW/fftw3/blob/e9c510bf92a4fa848982310d2ecc8c5701aa3f6a/kernel/kalloc.c#L104).

The `conda-forge` version is probably compiled with `gcc`, which is why `fftw_free` worked.

**Comment by sbrisard** [comment]
Thank you for this answer.
I have solved the problem with your help.
