### ISSUE TITLE
Problem initializing plan

### ISSUE THREAD

**Issue by zecarlosalmeida** [FFTW/fftw3#28]
Hi.
I'm trying to use snd2fftw (http://snd2fftw.sourceforge.net/) to aplly DFT on audio file, but I receive the error: Fail to initialize FFTW plan.
The author has no more support to the software. What can be this?

**Comment by rossry** [comment]
I understand that this is a bug in snd2fftw rather than fftw, but this is the first Google result for "Fail to initialize FFTW plan.", so I figured I'd update the thread with the actual fix:

At lines [404](http://sourceforge.net/p/snd2fftw/code/HEAD/tree/trunk/main.c#l404) and [532](http://sourceforge.net/p/snd2fftw/code/HEAD/tree/trunk/main.c#l532) of [main.c](http://sourceforge.net/p/snd2fftw/code/HEAD/tree/trunk/main.c), snd2fftw calls fftw_plan_dft_r2c_1d with flags=FFTW_FORWARD, which [isn't a valid flag](http://www.fftw.org/fftw3_doc/Planner-Flags.html) for fftw_plan_dtf_*. The easiest fix is to pass FFTW_MEASURE (or FFTW_ESTIMATE) instead.

(This worked for me, with FFTW 3.3.8 installed on Linux, after making a few separate Windows->Linux portability patches.)

I'll submit a request for a fix to the author, but the source hasn't seen updates in >5 years, so future users may just have to manually patch themselves.
