### ISSUE TITLE
Performance issue on Windows 8

### ISSUE THREAD

**Issue by juliohm** [FFTW/fftw3#63]
I have developed a package in Julia that uses FFTW for convolving 3D images. The code runs fast in most platforms, but my colleagues are experiencing a huge slowdown in a set of computers in our university with Windows 8. I opened an issue in the Julia project (https://github.com/JuliaLang/julia/issues/16570) and most people suspect that this is an issue with the FFTW version installed there or the way it was compiled.

How can I check the FFTW version that I have in the university? Do you know any possible cause for this huge slowdown (5min --> 95min)?

Thank you.

**Comment by juliohm** [comment]
Can anyone share some thoughts on this issue?

**Comment by dfarns** [comment]
You could print the wisdom, the first line will have the FFTW version.

**Comment by juliohm** [comment]
@dfarns besides the FFTW version, do you have any guess for the root of the issue? One thing that I am doing "incorrectly" in the code is planning the FFT at every call. I will refactor the code in the future, but I don't believe it is the cause of the issue since it is fast in other machines.

**Comment by juliohm** [comment]
There is any other issue tracker for FFTW that is preferred by the community? I am finding it strange that such a major performance issue is not getting the attention of the maintainers.

**Comment by matteo-frigo** [comment]
Julio,

the reason why you are not getting any answers is that there is not enough information in your question to help you.  Besides, we don't use Windows and in fact we avoid it like the plague.

Come up with a small reproducible example of the issue, and hopefully we can make progress based on that.

**Comment by juliohm** [comment]
Matteo,

I linked the issue with the original issue in the Julia issue tracker. You
can find a minimum working example there and many other useful profiling
reports.

Could you please check it again?

-Júlio

**Comment by ihnorton** [comment]
I tried a few [tests](https://github.com/JuliaLang/julia/issues/16570#issuecomment-257901256) with @juliohm's Julia example, and saw a slowdown when using more threads than physical cores:

19000s with `julia> FFTW.set_num_threads(8)`
700s with `set_num_threads(1)`
374s with `set_num_threads(4)`

(Windows 10; Intel [i7-3940xm](http://ark.intel.com/products/71096/Intel-Core-i7-3940XM-Processor-Extreme-Edition-8M-Cache-up-to-3_90-GHz) with 4 physical cores, 8 logical)

So at least a partial explanation and work-around. I'm still a bit puzzled though, because I can't reproduce the slowdown on simpler problems. I'll have to step through the usage in the referenced codes and try to reduce.
